version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - model_data:/app/models
    restart: unless-stopped

  cron:
    build: 
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - model_data:/app/models
    restart: unless-stopped
    depends_on:
      - app

volumes:
  model_data:
